// TEST
### Home Page
GET http://localhost:8080

### Get All Contacts
GET http://localhost:8080/contacts

### Get Single Contact
GET https://localhost:8080/contacts/696a64decc5d9b21c40ef943

// PRODUCTION
### Home Page
GET https://cse341-project1-k1om.onrender.com

### Get All Contacts
GET https://cse341-project1-k1om.onrender.com/contacts

### Get Single Contact
GET https://cse341-project1-k1om.onrender.com/contacts/696a64decc5d9b21c40ef943